create table pco_instance (
	pco_id int unsigned not null auto_increment,
	pco_name char(21) not null,
	pco_ip int unsigned not null,
	chn0_lbl char(21) not null,
	chn0_OnDelay tinyint unsigned not null,
	chn0_OffDelay tinyint unsigned not null,
	chn0_reboot tinyint unsigned not null,
	chn0_occlude  boolean not null,
	chn1_lbl char(21) not null,
	chn1_OnDelay tinyint unsigned not null,
	chn1_OffDelay tinyint unsigned not null,
	chn1_reboot tinyint unsigned not null,
	chn1_occlude  boolean not null,
	chn2_lbl char(21) not null,
	chn2_OnDelay tinyint unsigned not null,
	chn2_OffDelay tinyint unsigned not null,
	chn2_reboot tinyint unsigned not null,
	chn2_occlude  boolean not null,
	chn3_lbl char(21) not null,
	chn3_OnDelay tinyint unsigned not null,
	chn3_OffDelay tinyint unsigned not null,
	chn3_reboot tinyint unsigned not null,
	chn3_occlude  boolean not null,
	chn4_lbl char(21) not null,
	chn4_OnDelay tinyint unsigned not null,
	chn4_OffDelay tinyint unsigned not null,
	chn4_occlude  boolean not null,
	chn5_lbl char(21) not null,
	chn5_OnDelay tinyint unsigned not null,
	chn5_OffDelay tinyint unsigned not null,
	chn5_occlude  boolean not null,
	chn6_lbl char(21) not null,
	chn6_OnDelay tinyint unsigned not null,
	chn6_OffDelay tinyint unsigned not null,
	chn6_occlude  boolean not null,
	chn7_lbl char(21) not null,
	chn7_OnDelay tinyint unsigned not null,
	chn7_OffDelay tinyint unsigned not null,
	chn7_occlude  boolean not null,
	bank tinyint unsigned not null default 0,
	primary key (pco_id)
);
